---
title: "Package dqassess introduction"
author: "Mathieu Depetris (mathieu.depetris@ird.fr)"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  word_document: default
  html_vignette: default
vignette: >
  %\VignetteIndexEntry{Package dqassess definition data format}
  \usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown}
---

- [Background and context](#background-and-context)
- [Purpose of this package](#purpose-of-this-package)
- [Package framework](#package-framework)

# Package dqassess: procedures to assess the quality of large pelagic data

## Background and context

This package was developed under the cover of the European project MARE/2016/22 « Strengthening regional cooperation in the area of fisheries data collection » Annex III « Biological data collection for fisheries on highly migratory species » (acronym: RECOLAPE). He answered the aims of the two first task of the Work Package 5: propose procedures for data quality assessment, at national and regional levels, in the area of large pelagic fisheries data collection.

## Aim of this package

The main objective of this package concerns the development of data quality assessment procedures. Within the framework of the regional cooperation, it’s crucial to ensure that the data transmitted to the end users have undergone common quality assessment procedures. 

As a minimum, we should check the data quality at two important steps of the data flow:

- At the national scale, before the transmission to the regional coordination group,
- At the regional scale, after building the regional dataset and before the transmission to end users.

## Package framework

This package was design with a simple thought: quality and associated processes have to be in constant improvement!

Indeed, the structure package was developped to maximize compatibility with futur updated and addition of specific controls and tests. Furthermore, it must be seen as a bridge to systems more transversal and interconnected, like the new RDBES (Regional Data Base and Estimation System), under developpement by the International Council for the Exploration of the Sea (ICES). Otherwise, several other projects, like the WP6 of the FishPi2 project or the futur evolutions of the COST R package, have common guideline and goals. These projects were not avaible yet, but it could be very interesting to working with and develop common processes.

For now, the package source was stored on a public repository loacated on [GitHub](https://github.com/OB7-IRD/dqassess.git). This is web-based hosting service for version control system or tracking changes. In addition of storage and tracking changes, this platform allowed a system to track todos, bugs or feature requests. This working by using "Issues" menu throught the following [link](https://github.com/OB7-IRD/dqassess/issues/new). All contributions and feeback experiences on should increase the relevance and the robustness of this package and also serve the interest the large pelagic community people.
